name: counter_edge_functions
description: A Supabase Edge Functions example written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.5
  edge_http_client: ^0.0.1+1
  supabase: ^1.6.3
  supabase_functions: ^0.0.1

dev_dependencies:
  lints: ^2.0.1