name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  counter_edge_functions:
    path:  '../edge_functions'
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
